
namespace SuperSeedSearch.ConstantEnum
{
    public class MultiLineText
    {
        public const string Welcome = "Welcome Seed Searcher! \n Super Seed Search mod let you search world seeds which generate vanilla Terraria worlds with specific properties you are looking for. That means the seeds found here can also work without any mods (*)."+
                                    " Or as alternative this mod can also be used to just find some nice worlds with e.g. many Pyramids, a Living Tree near spawn and no Corruption in Jungle biome. \n \n" +
                                    " With 1.4+ world generation changed a lot. To adapt and to make the mod more powerful it got some new internal structure and with this almost all need to be implemented again. It will take some time" +
                                    " until all features (which are still possible) of it's 1.3.5 equivalent are implement. You can join the mod's Discord channel (discord.gg/6HXKa9a) to have some impact about the next upcoming features or"+
                                    " just to be part of the Seed Searcher community. \n \n"+
                                    " How does the mod work? \n During world generation it checks if the world matches the chosen search criteria - if not the mod ends world generation of the current seed and continue with the next seed." +
                                    " Some criteria can be checked at early world generation, some other need more world gen steps and some even the full world generation. Depending on chosen criteria it can be over a thousand times faster" +
                                    " than normal world gen or just about the same speed. Hint for set up search criteria: There will be some '#number' - the smaller the 'number' the faster it can be checked. \n \n" +
                                    " How to set up search criteria? \n At the top left there is the search tab bar starting with 'Main', '1', '+'. \n 'Main' tab is for general settings about the search \n"+
                                    " '1' is the tab of the first search query. During search the world generated by the current seed need to pass all conditions with their related constraints entered here to count as accepted \n"+
                                    " '+' adds another search query tab. This can be used to do multiple search queries at the same time. \n To pass only one of those queries need to be fulfilled. Tabs marked as global need to be true as well. \n \n"+
                                    " Some more hints: \n"+
                                    " Distances, height and similar use world tiles as unit, so e.g. a distance of 5 means 5 tiles away (equal to 10 feet). Path length tries to be an equivalent if e.g. a solid tile blocks the way" +
                                    " it will increase the path length by that many tiles which could have been walked during the mining process. \n"+
                                    " Don't be too strict at your first searches. Best practice is to start with easy-to-fulfill conditions, test if they work out, tighten them or add new, test again and so on. \n" +                                    
                                    " (*): tModloader and with this also this mod generate slightly different worlds than in vanilla Terraria. With 1.4.4.9 those differences are very minor and only happen on seed depended x-coordinates. Mostly just different stalactite placement. In rare cases gem-trees. \n \n \n"+
                                    " Have fun & good luck in finding the seeds of your dreams! \n "; 

    }
}